
export const INTEREST_QUESTIONS = [
  { id: 'mentors', label: 'Ce interese ai datorită anumitor mentori din viața ta?' },
  { id: 'family', label: 'Ce interese ai în comun cu tatăl, mama, fratele sau sora ta?' },
  { id: 'friends', label: 'Ce interese ai datorită prietenilor?' },
  { id: 'school', label: 'Ce interese ai datorită școlii, sportului și comunității?' },
  { id: 'church', label: 'Ce interese ai datorită implicării în biserică?' },
  { id: 'location', label: 'Ce interese ai datorită locului în care locuiești?' },
  { id: 'opportunities', label: 'Ce interese ai datorită oportunităților?' },
  { id: 'talents', label: 'Ce interese ai datorită talentelor sau abilităților unice?' },
];

export const SPIRITUAL_GIFTS_QUESTIONS = [
  "Am o sensibilitate deosebită în recunoașterea gândurilor sau impresiilor care sunt de la Duhul Sfânt.",
  "Răspund liber și dornic la cererile de suport financiar în lucrările/eforturile creștine care merită.",
  "Găsesc bucurie în asumarea rolurilor de rutină a responsabilităților altora în scop de a-i elibera pentru alte lucruri.",
  "Utilizând cunoștințele care nu originează în mine însumi, recunosc situațiile în care Duhul vrea să lucreze.",
  "Am dorință mare de a oferi încurajare și direcție celor care sunt în nevoi, stres sau iau decizii importante în viață.",
  "Când vorbesc sau acționez ca lider, oamenii de obicei ascultă, sunt de acord și urmează opinia sau conducerea mea.",
  "Am prieteni necreștini cărora le fac mărturii direct și indirect.",
  "Oamenii s-au simțit încurajați pentru că am dorit să le ofer călăuzire și susținere pentru o perioadă extinsă de timp.",
  "Simt o grijă deosebită pentru starea spirituală a creștinilor care se află în situații de criză.",
  "Aș vrea să mă implic în ajutorarea vagabonzilor.",
  "Am dorința de a proclama adevărul pe care l-am primit de la Dumnezeu cu autoritate și convingere.",
  "Îmi place să prezint promisiunile lui Dumnezeu din Scriptură ca modalitate de a-i încuraja pe alții.",
  "Văd sarcini practice care trebuie îndeplinite și le fac în liniște fără ca alții să observe.",
  "Mă simt confortabil petrecând timp cu necreștinii, fiind în stare niciodată să nu-mi compromit credința, însă căutând de a fi o lumină pentru ei.",
  "Îmi găsesc plăcerea în elaborarea detaliilor necesare ce țin de organizarea oamenilor și resurselor pentru o lucrare mai eficientă.",
  "Îmi place să inspir și să conduc pe alții de dragul lucrării lui Cristos.",
  "Au fost cazuri când am crezut că Dumnezeu poate face imposibilul și am văzut aceasta în realitate.",
  "Am experimentat o înțelegere imediată a unor lucruri despre oameni fără a afla această informație prin căi obișnuite.",
  "Am avut visuri și aspirații mari care s-au transformat în realitate în ciuda imposibilității realizării lor.",
  "Când consiliez o persoană, pot identifica problema corect.",
  "Am capacitatea de a vedea “tabloul mare” al unui proiect și pot coordona pe alții care văd părțile componente diverse.",
  "Îmi place să fac donații anonime atunci când îmi împart resursele financiare și materiale cu alții.",
  "Se pare că am capacitatea de a vedea cum Dumnezeu lucrează în viețile oamenilor, chiar și în timp de încercare.",
  "Îmi place să mă ocup de sarcinile mici care întăresc trupul lui Cristos.",
  "Cred cu fermitate că unele persoane, inclusiv și eu personal, ar trebui să dea mai mult decât zeciuiala (10%) din venitul lor pentru lucrarea Domnului.",
  "Deseori simt prezența binelui sau răului într-o persoană.",
  "Oamenii au tendința să mă cheme când e nevoie de a ajuta pe cineva în situație de stres.",
  "Când vorbesc cu oamenii unu-la-unu, deseori sunt provocați la niște acțiuni pozitive.",
  "Îmi pasă foarte mult de cei care nu L-au primit pe Cristos și simt că Dumnezeu mă poate folosi pentru atingerea lor.",
  "Slujirea altora are prioritate pe lista mea, indiferent de sarcină.",
  "Am fost de folos în conducerea altora în a-L primi pe Cristos ca Salvator personal.",
  "Am capacitatea de a crede în împlinirea planurilor lui Dumnezeu mai presus de așteptările normale sau probabile.",
  "Îmi place să studiez Biblia în așa mod în care să găsesc aplicare personală la ceea ce studiez.",
  "Mă găsesc lucrând în spatele scenei fără nevoia de a fi recunoscut în public.",
  "Se pare că pot să cunosc când o situație nu este corectă din punct de vedere spiritual sau moral.",
  "Când sunt confruntat cu o problemă complexă, pot să definesc centrul problemei și să iau măsuri pentru a o rezolva.",
  "Se pare că am o capacitate specială de a simți gândirea Duhului Sfânt.",
  "Doresc să le stau la dispoziția celor pe care îi încurajez spiritual.",
  "Dumnezeu mi-a descoperit situațiile sau problemele oamenilor.",
  "Am dus mesaje urgente din partea Cuvântului lui Dumnezeu referitor la prezent sau viitor.",
  "Deseori îmi rearanjez orarul/programul pentru a-i ajuta pe alții.",
  "Demonstrez încredere convingătoare în Dumnezeu în ciuda obstacolelor aparente și contribui la creșterea viziunii și încrederii altor creștini din Trup.",
  "Pot lucra sub presiune pentru atingerea scopurilor și obiectivelor.",
  "În timpul discutării și împărtășirii unei probleme, eu prezint într-un fel în care să se clarifice cele necesare pentru rezolvarea problemei.",
  "Întotdeauna strâng haine, obiecte de uz casnic și hrană pentru cei nevoiași.",
  "Pot să prezint Evanghelia într-un fel în care ea devine clară și are sens pentru necredincioși.",
  "Aplic adevărul spiritual într-un mod eficient în viața mea.",
  "Contribuția pe care o aduc cu resursele mele materiale și financiare pentru lucrarea creștină este unul din lucrurile care îmi provoacă bucurie în umblarea mea creștină.",
  "Pregătirea meselor sau ajutorarea celor care au mai puțin ca mine îmi dă mare satisfacție și plăcere.",
  "Cu toate că poate fi dificil, aș dori să îndeplinesc rolul de conducere dacă ar fi nevoie de a disciplina pe cineva din biserică.",
  "Aș vrea să mă fac disponibil pentru a fi folosit pentru orice fel de datorie sau rol în biserică.",
  "Am obținut discernământ spiritual din scriptură referitor la anumite persoane sau probleme, ceea ce m-a făcut să vreau să vorbesc despre aceasta.",
  "Starea spirituală de lungă durată a familiei, prietenilor și cunoscuților e foarte importantă pentru mine.",
  "Îmi place să comunic adevărul biblic altora și să văd creșterea lor în cunoașterea credinței creștine.",
  "Pot să fac deosebirea dintre lucrarea cărnii și a roadelor Duhului.",
  "Alții îmi spun că pot obține adâncire în adevărul biblic datorită unui studiu biblic condus de mine.",
  "Am avut cazuri când am știut îndată de ce are nevoie o persoană sau un grup fără să știu cum am obținut această informație.",
  "Simt că Dumnezeu mi-a vorbit prin Duhul Său, oferind direcție și călăuzire spirituală pentru mine însumi, familia mea sau un grup de credincioși.",
  "Împart în mod deschis posesiunile mele cu alții când sunt în nevoie (adică unelte, mașină, etc.)",
  "Îmi plac proiectele orientate spre o sarcină mai mult decât cele orientate spre o persoană sau cele de tip unu-la-unu.",
  "Îmi place să ofer călăuzire și direcționare în discutarea realizării scopurilor și obiectivelor spirituale a unui grup.",
  "Am contribuit cu cunoștințe spirituale la soluționarea conflictelor sau problemelor din cadrul Trupului lui Cristos.",
  "Oamenii deseori sunt uimiți de înțelepciunea mea, cu toate că nu am multe studii academice.",
  "Îmi plac sarcinile de termen scurt mai multe decât proiectele de lungă durată.",
  "Simt împreună cu oamenii care suferă și traduc emoțiile mele în acțiune.",
  "Oamenii mi-au spus că i-am ajutat să crească spiritual.",
  "Alții din biserică au confirmat că pot « simți » motivele din inima unei persoane.",
  "Oamenii mă caută când au nevoie de călăuzire pentru planificare și dirijarea unei sarcini anumite din lucrare.",
  "Pot vorbi cu entuziasm și claritate despre adevărul doctrinal, oferind sprijin, călăuzire, avertizare sau încurajare.",
  "Sunt încredințat că atunci când dau cu jertfire, Domnul se va îngriji de toate nevoile mele.",
  "Am împărtășit adevărul biblic cu alții într-un mod care a fost util și pe înțelesul lor.",
  "Primesc o bucurie și pace nespusă când mă ocup de procesul de ucenicie în umblarea spirituală a altora.",
  "Cu încredere aștept ca Dumnezeu va răspunde la situațiile pe care I le-am încredințat în rugăciune.",
  "Mă satisface mult când îi învăț pe alții adevărurile biblice pe care le-am învățat prin studiu biblic.",
  "Oamenii tind să se uite la mine ca la un lider când sunt într-un grup."
];

export const PERSONAL_STYLE_ORGANIZE = [
  { left: "fiu spontan", right: "urmez un plan stabilit" },
  { left: "generală", right: "specific" },
  { left: "fiu deschis oportunităților", right: "hotărăsc lucrurile acum" },
  { left: "varietate", right: "rutină" },
  { left: "improvizez", right: "respect un plan" },
  { left: "plictisitoare", right: "odihnitoare" },
  { left: "lucrând din mers", right: "urmând un plan" },
];

export const PERSONAL_STYLE_ENERGIZE = [
  { left: "ajut pe alții", right: "petrec timp cu alții" },
  { left: "sa ma concentrez asupra scopului", right: "sa ma concentrez asupra relațiilor" },
  { left: "promovarea unei cauze", right: "crearea unei comunități" },
  { left: "am terminat de făcut o lucrare", right: "am zidit o relație" },
  { left: "la timp", right: "când toți sunt prezenți" },
  { left: "respectarea termenului stabilit", right: "menținerea echipei" },
  { left: "acțiune", right: "comunicare" },
];

export const PASSION_QUESTIONS = [
  { id: 'pastProblems', label: '1. Ce lucruri din trecut au cauzat probleme în viața ta care te împiedică să-ți urmezi cu pasiune chemarea în slujire? Cum ai putea proceda pentru a-i „uita”?' },
  { id: 'objectives', label: '2. Ce „obiective” din viața ta te entuziasmează? (Ce fel de conversație te ține treaz până noaptea târziu?)' },
  { id: 'endOfLife', label: '3. La sfârșitul vieții, mi-ar place sa pot privi înapoi și să știu că am făcut ceva legat de:' },
  { id: 'forOthers', label: '4. Ceea ce mi-ar place cel mai mult să fac pentru alții este:' },
  { id: 'peopleToHelp', label: '5. Oamenii pe care mi-ar plăcea sa-i ajut cel mai mult sunt (ex: bebelușii, copiii, tinerii, mamele adolescente, cei divorțați, femeile de cariera, familii, șomerii, pușcăriașii, părinții singuri, cei văduvi, cei singuri, bătrânii, săracii, studenții, refugiați, cei fără adăpost, invalizi, cei spitalizați, alții):' },
  { id: 'causes', label: '6. Problemele sau cauzele de care îmi pasă cel mai mult sunt (ex: mediul înconjurător, îngrijirea copiilor, homosexualitatea, ucenicizarea, violenta, educația, economia, sănătatea, avortul, biserica, SIDA, nedreptatea, aducțiile, sărăcia, politica, rasismul, tehnologia, familia, alfabetizarea, problemele internaționale, altele):' },
  { id: 'positiveExperiences', label: '7. Gândește-te la 3-5 experiențe pozitive care le-ai avut in viață. Ce a fost semnificativ pentru tine in toate aceste experiențe? E vorba de experiențe care ți-au adus împlinire, bucurie.' },
  { id: 'calling', label: '8. Spre ce crezi că te „cheamă” Dumnezeu? (Sumarizează domeniile preocupărilor tale.)' },
];

export const OPPORTUNITIES_QUESTIONS = [
  { id: 'personalProblems', label: '1. Care sunt unele dintre cele mai mari probleme și/sau provocări din viața ta personală?' },
  { id: 'personalOpportunities', label: '2. Ce oportunități de lucrare ar putea exista ca urmare a acestor probleme și provocări?' },
  { id: 'familyProblems', label: '3. Care sunt unele dintre cele mai mari probleme și/sau provocări din căsnicia și/sau familia ta?' },
  { id: 'familyOpportunities', label: '4. Ce oportunități de lucrare ar putea exista ca urmare a acestor probleme și provocări?' },
  { id: 'friendsProblems', label: '5. Care sunt unele dintre cele mai mari probleme și/sau provocări în rândul prietenilor tăi?' },
  { id: 'friendsOpportunities', label: '6. Ce oportunități de lucrare ar putea exista ca urmare a acestor probleme și provocări?' },
  { id: 'churchProblems', label: '7. Care sunt unele dintre cele mai mari probleme și/sau provocări din biserica dumneavoastră și/sau din bisericile din comunitatea dumneavoastră?' },
  { id: 'churchOpportunities', label: '8. Ce oportunități de lucrare ar putea exista ca urmare a acestor probleme și provocări?' },
  { id: 'communityProblems', label: '9. Care sunt unele dintre cele mai mari probleme și/sau provocări din comunitatea dumneavoastră?' },
  { id: 'communityOpportunities', label: '10. Ce oportunități de lucrare ar putea exista ca urmare a acestor probleme și provocări?' },
  { id: 'equipmentNeeded', label: '11. Ce fel de lucruri crezi că trebuie să înveți sau să te echipezi pentru a face ceva în privința acestor probleme și provocări (tot ce ai scris pentru întrebările 1-8)?' },
];

export const SPIRITUAL_EXPERIENCE_QUESTIONS = [
  { id: 'savedFrom', label: '1a) Din ce aspecte ale vieții tale te-a scos Domnul Isus (sau cel puțin parțial)? (Fii specific - ex: dependențe, furie, depresie, relații destrămate, ocultism, furt, minciună, egoism, amânare, lene, atitudine negativă, bârfă, calomnie, mândrie etc.)' },
  { id: 'notYetLord', label: '1b) În ce domeniu al vieții tale Isus încă nu este Domnul? (Fii specific - adică bani, sex, program (timp), căsătorie, familie, prieteni, muncă, recreere, cuvinte, ambiții, vise, obiective, emoții, atitudini, viziune asupra lumii, dorințe etc.)' },
  { id: 'guiltPaid', label: '1c) Pentru ce fel de vinovăție din viața ta a plătit Isus prețul pe cruce? (Fii specific. Nu scrie doar „întreaga vinovăție”.)' },
  { id: 'painRemoved', label: '1d) Ce durere a înlăturat Isus din viața ta?' },
  { id: 'burdensTaken', label: '1e) Ce lucruri care te împovărează (poverile) te-a luat Isus?' },
  { id: 'discouragementToCourage', label: '1f) Ce descurajări a transformat Isus în curaj?' },
  { id: 'sufferingAlleviated', label: '1g) Ce suferințe a alinat Isus în viața ta?' },
  { id: 'savedFor', label: '2a) Am fost mântuit pentru... (Ex. El te-a mântuit ca să poți începe o lucrare, să fii implicat într-o lucrare, să slujești eficient la locul de muncă, să crești o familie creștină, să plantezi o biserică, să conduci un studiu biblic, să fii un mentor pentru alții, să fii implicat într-o lucrare muzicală etc.)' },
  { id: 'generalExperiences', label: '3a) Ce experiențe generale ați avut? (adică, locul de muncă, familia, căsătoria, biserica, strada, sportul, timpul liber, călătoriile, conducerea, afaceri etc.)' },
  { id: 'howExperiencesHelp', label: '3b) Cum te-ar putea ajuta aceste experiențe în lucrare?' },
];
